### ISSUE TITLE
Wrong url in Request.JSON page

### ISSUE THREAD

**Issue by ricardograca** [mootools/website#206]
Right at the top there's a link to the Request page, however the link's url is incorrect.

Current: `http://mootools.net/Request/docs/1.5.1/Request/Request`
Expected: `http://mootools.net/core/docs/1.5.1/Request/Request`

**Comment by SergioCrisostomo** [comment]
Thank you @ricardograca will check it out.

The docs have different syntax of markdown. Both:

    [Request](/Request/Request)
and

    [Request]: /core/Request/Request

We could either fix this in newest docs version (in the Core repo), or add one more exception while compiling so all older versions will compile correct... :grey_question:

**Comment by SergioCrisostomo** [comment]
Hi @ricardograca!

I think this has been fixed in the past and this issue was not closed then.
I close it now as I cannot see the problem anymore.

Obrigado!
(oh, and please do reopen if I am wrong)

**Comment by ricardograca** [comment]
It's still not fixed, but I can't reopen it. Clicking on the link to [Request](http://mootools.net/Request/docs/1.5.1/Request/Request) still produces an error:

> Oops, this is not the page you're looking for...

**Comment by SergioCrisostomo** [comment]
@ricardograca ok, I see the problem now and will fix it. 
Thanks for fast feedback.
